[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib', '../../../lib', '../../../node_modules']
solc_version = '0.8.19'
fs_permissions = [
    { access = 'read', path = './' }
]
remappings = [
    "test/=test/",
    "@openzeppelin/contracts=../../../node_modules/@openzeppelin/contracts/"
]
evm_version = 'shanghai'